In [2]:
import numpy as np


In [3]:
mylist=[1,2,3]
myarray = np.array(mylist)
type(myarray)


numpy.ndarray

arange

In [ ]:
arr=np.arange(0,11,2)
print(arr)
arr1=arr.reshape(2,3)
print(arr1)

[ 0  2  4  6  8 10]
[[ 0  2  4]
 [ 6  8 10]]


In [ ]:
np.zeros((2,5)).astype(int)


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

linspace - linearly spaced array

In [ ]:
np.linspace(0,10,3)
np.linspace(0,10,3).astype(int)

array([ 0,  5, 10])

eye - returns a 2d array with ones on the diagonals amd zeros elsewhere

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

random


In [34]:
np.random.rand(1)


array([0.85794562])

In [ ]:
np.random.rand(5,2)

array([[0.86125877, 0.42711942],
       [0.45380177, 0.56780696],
       [0.42074901, 0.61650337],
       [0.12256687, 0.99025447],
       [0.92969301, 0.41653314]])

randint  to generate an integer randomly, within the range.
We can also specify the number of integer required. It will be returned as array.
Also specify tuple, for the array dimension.

In [ ]:

np.random.randint(1,10,3)

array([4, 7, 1])

In [ ]:
np.random.randint(1,10,(2,3))

array([[4, 3, 4],
       [4, 8, 9]])

seed will preserve the random numbers.
It is recommended not to use seed, which will have global impact.
Instead create a rng object using np.random.defauflt_rng(seed)

In [37]:
np.random.seed(42) # not recommended
print(np.random.randint(1,10,3))





[7 4 8]


In [36]:
rng =np.random.default_rng(42) #here 42 is seed
print(rng.random())
rng1 =np.random.default_rng(42) #here 42 is seed
print(rng.uniform(high=20))
print(rng1.uniform())

0.7739560485559633
8.777568795041047
0.7739560485559633


SLICING
    used to get portions of array

In [42]:
ar=np.arange(1,10)
print(ar)
print(ar[0:])
print(ar[:])
print(ar[5:])

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[6 7 8 9]


Broadcasting
    used to perform oerations at once to the entire array


In [55]:
print(ar*2)
print(ar)

slice_of_array=ar[:5]
slice_of_array[:]=100
print(slice_of_array)
print(ar)

[200 200 200 200 200  12  14  16  18]
[100 100 100 100 100   6   7   8   9]
[100 100 100 100 100]
[100 100 100 100 100   6   7   8   9]


array copy
use ar.copy to avoid above effect on array

In [1]:
arr_copy=ar.copy()


NameError: name 'ar' is not defined

two dimensional array
# slicing operation 
# first one is row and second is column
use np.vstack to stack vertically

In [60]:
twod_array=np.arange(5,50,5)
twod_array=np.arange(5,50,5)
print(twod_array)
type(twod_array)
# print(twod_array.reshape(3,3))

# slicing operation 
# first one is row and second is column
twod_copy=twod_array.reshape(3,3)
print(twod_copy)
print(twod_array)

print(twod_copy[0,:])

print(twod_copy[:,0])

print(twod_copy[0,0])

print(twod_copy[-1,-1])
print(twod_copy[2,2])

twod_copy_reshape=twod_copy[0,:].transpose()

print(np.vstack(twod_copy_reshape))

[ 5 10 15 20 25 30 35 40 45]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
[ 5 10 15 20 25 30 35 40 45]
[ 5 10 15]
[ 5 20 35]
5
45
45
[[ 5]
 [10]
 [15]]


conditional selection in numpy

In [68]:
arr=np.arange(1,10,)
arr1=arr[arr>3]
print(arr1)

[4 5 6 7 8 9]


numpy operations



In [86]:
arr=np.arange(0,5)

arr+arr
arr*2
arr/arr

np.sqrt(arr)

np.log(arr)

arr.sum()
arr.max()



C:\Users\jogym\AppData\Local\Temp\ipykernel_9464\1952048925.py:5: RuntimeWarning: invalid value encountered in true_divide
  arr/arr
C:\Users\jogym\AppData\Local\Temp\ipykernel_9464\1952048925.py:9: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


4

operations on 2d

In [91]:
arr=np.arange(0,25).reshape(5,5)
print(arr)
# arr.sum(0) # this will give the sum of columns
# arr.sum(1) # this will give  sum of rows

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
